version: 2
jobs:
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2

    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f docker/docker-compose.yml up -d --build

      - run:
          name: Wait container is ready
          command: |
            set -x
            sleep 20


      - deploy:
          name: Deployment
          machine:
            enabled: true
          steps:
            - run:
              name: Deploy Over SSH
              command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ssh -oStrictHostKeyChecking=no vhugo@csi.splab.ufcg.edu.br /opt/deploy/morajunto.sh
              fi

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
