version: '3'

services:
  spring:
    build: .
    container_name: spring
    image: spring
    ports:
      - "8099:8080"
    volumes:
      - ../:/opt/spring/
      - maven:/root/.m2/
    environment:
      - BANNER_LOCATION=file:/config/banner.txt

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: --bind_ip 0.0.0.0
    expose:
      - "27017"

volumes:
  maven:
  mongo:
