version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: --bind_ip 0.0.0.0
    expose:
      - "27017"
    ports:
      - "27017:27017"

volumes:
  mongo:
